[project]
name = "blasteroids"
version = "0.1.0"
description = "Blast your way through flying spcae rocks in this asteroids like game."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pygame==2.6.1",
]
